# Generated by Django 4.2.4 on 2023-08-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='due_date',
            new_name='duedate',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
    ]
