# Generated by Django 4.2.4 on 2023-08-07 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_due_date_project_duedate_project_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='duedate',
            new_name='dueDate',
        ),
    ]
