# Generated by Django 4.2.4 on 2023-08-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='dueDate',
        ),
    ]
