# Generated by Django 4.2.4 on 2023-08-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_due_date_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
    ]
