# Generated by Django 4.2.4 on 2023-08-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('To Do', 'To Do'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='New', max_length=20),
        ),
    ]
